# Generated by Django 3.1.4 on 2020-12-28 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='books'),
            preserve_default=False,
        ),
    ]
